CREATE TABLE `oa`.`o_file` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '档案id',
  `name` VARCHAR(18) NOT NULL COMMENT '姓名',
  `gender` INT NOT NULL COMMENT '性别',
  `age` INT NOT NULL COMMENT '年龄',
  `mobile_phone` VARCHAR(20) NOT NULL COMMENT '移动电话',
  `QQ` VARCHAR(20) NOT NULL COMMENT '分机号',
  `birthday` DATE NOT NULL COMMENT '出生日期',
  `marry_status` INT NOT NULL COMMENT '婚姻状态',
  `native_place` VARCHAR(45) NOT NULL COMMENT '籍贯',
  `domicile` VARCHAR(45) NOT NULL COMMENT '户口所在地',
  `politics` INT NOT NULL COMMENT '政治面貌',
  `IDcard` VARCHAR(18) NOT NULL COMMENT '身份证号',
  `health` INT NOT NULL COMMENT '健康状况',
  `blood_type` INT NOT NULL COMMENT '血型',
  `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
  `graduation` VARCHAR(45) NOT NULL COMMENT '毕业院校',
  `discipline` VARCHAR(45) NOT NULL COMMENT '专业',
  `study_level` INT NOT NULL COMMENT '学历',
  `degree` INT NOT NULL COMMENT '学位',
  `language` INT NOT NULL COMMENT '语种',
  `language_level` VARCHAR(20) NOT NULL COMMENT '外语水平',
  `certificate` VARCHAR(255) NOT NULL COMMENT '证书',
  `file_location` VARCHAR(45) NOT NULL COMMENT '档案所在地',
  `work_length` INT NOT NULL COMMENT '工作经验（时间）',
  `join_date` DATE NOT NULL COMMENT '入职日期',
  PRIMARY KEY (`id`));
  